config/routes.rb
Rails.application.routes.draw do

  resources :favorites, only:[:create,:destroy]
  resources :sessions, only:[:new,:create,:destroy]
  resources :users, only:[:index,:show,:new,:create]
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites,source: :user
  validates :title, presence: true, length: {maximum: 25}
  validates :content, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :favorites, dependent: :destroy
  before_validation {email.downcase!}
  validates :name, presence: true, length: {maximum: 25}
  validates :email, presence: true, length: {maximum: 25},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def require_logged_in
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path,notice:"#{favorite.user.name}さんをお気に入り登録"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path,notice:"#{favorite.user.name}さんのお気に入り解除"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in

  def index
    @posts = Post.all.order('updated_at DESC')
  end

  def confirm
    @post = current_user.posts.new(post_params)
    if @post.invalid?
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @favorite = Favorite.find_by(post_id: @post.id)
  end

  def new
    if params[:back]
      @post = Post.new(post_params)
    else
      @post = Post.new
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] ='Posted!!'
      redirect_to posts_path
    else
      flash.now[:danger] ='Failed..'
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] ='Edit completed'
      redirect_to posts_path
    else
      flash[:danger] ='Failed..'
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:danger] ='Deleted!'
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title,:content,:user,:image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] ="logged in!!"
      redirect_to users_path
    else
      flash[:danger] ="Failed.."
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:danger] ="log out!!"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only:[:index,:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] ="Sign up!"
      redirect_to users_path
    else
      flash.now[:danger] ="Failed.."
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def choose_new_or_edit
    if action_name =='new'|| action_name =='confirm'
      confirm_posts_path
    elsif action_name =='edit'
      post_path
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error_explanation">
    <h4><%= model.errors.count %>件のエラーがあります</h4>
  </div>
  <ul>
    <% model.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type,msg| %>
<div class="alert alert-<%= type %>"><%= msg %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%=link_to "Fbook",posts_path,class:"navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="navbarEexample1">
			<ul class="nav navbar-nav">
				<% if logged_in? %>
					<li><%= link_to 'Profile',user_path(current_user.id) %></li>
					<li><%= link_to 'Logout',session_path(current_user.id),method: :delete %></li>
				<% else %>
					<li><%= link_to 'Sign up',new_user_path %></li>
					<li><%= link_to 'Login',new_session_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model:post,url:choose_new_or_edit,local:true)do |f|%>
<%= render 'layouts/error_messages',model: f.object %>

  <div class="post_group">
    <%= f.label :title,"Title" %>
    <%= f.text_field :title,class:'form-control' %>
  </div>

  <div class="post_group">
    <%= f.label :content,"Content"%>
    <%= f.text_field :content,class:'form-control'%>
  </div>

  <div>
    <%= f.label :image %>
    <%= image_tag @post.image.url if @post.image? %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <%= f.submit 'OK!',class:'btn btn-primary btn-block'%>
<% end %>

app/views/posts/confirm.html.erb
<h1>Are you ok?</h1>
<%=form_with(model:@post,url:posts_path,local:true)do |f|%>
  <%= f.hidden_field :title%>
  <%= f.hidden_field :content%>
  <%= f.hidden_field :image_cache%>

  <p>Title:<%= @post.title%></p>
  <p>Content:<%= @post.content%></p>
  <p>Image: <%= image_tag @post.image.url if @post.image?%></p>
  <%= f.submit 'OK!'%>
<% end %>

<%= form_with(model:@post,url:new_post_path,local:true,method:'get')do |f|%>
  <%= f.hidden_field :title%>
  <%= f.hidden_field :content%>ı
  <%= f.hidden_field :image_cache%>
  <%= f.submit 'Back!',name:'back'%>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Page</h1>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts index <%= link_to 'Create New Post',new_post_path,class:'btn btn-primary btn-lg' %></h1>
<ul class = "media-list">
  <%@posts.each do |post|%>
  	<li class="media">
      <%= link_to "#{post.user.name}:",user_path(post.user.id),class:"media-left" %>
  		<div class="media-body">
  			<h4 class="media-heading">
          <%= post.title %>
          <% if post.favorites.present?%>
            <span style='color:red;'>(^^)／</span>
          <% end %>
        </h4>
  			<%= post.content %>
  		</div>
      <div id='photo_image'>
        <% if post.image? %>
          <%= image_tag post.image.url %>
        <% else %>
          <p class = 'label label-default'>No Image</p>
        <% end %>
      </div>
      <div>
        <%= link_to 'Detail',post_path(post.id),class:'btn btn-primary btn-xs' %>
        <% if post.user_id==current_user.id %>
          <%= link_to 'Edit',edit_post_path(post.id),class:'btn btn-warning btn-xs'%>
          <%= link_to 'Delete',post_path(post.id),method: :delete,data:{confirm:'Are you sure?'},class:'btn btn-danger btn-xs'%>
        <% end %>
      </div>
  	</li>
  <% end %>
</ul>
<%= link_to 'Create New Post',new_post_path,class:'btn btn-primary btn-block'%>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>Post info.</h1>
<div class="jumbotron">
	<h1><%= @post.title%></h1>
	<h2>「 <%= @post.content%> 」</h2>
	<div>
		<% if @post.image? %>
		<%= image_tag @post.image.url %>
		<% else %>
		<p class='label label-default'>No Image</p>
		<% end %>
	</div>
	<p><%= link_to 'Back',posts_path,class:"btn btn-primary btn-lg" %>
</div>
<% unless @post.user_id==current_user.id %>
	<% if @favorite.present? %>
		<%= link_to 'お気に入り解除',favorite_path(id: @favorite.id),method: :delete,class:'btn btn-warning btn-lg'%>
	<% else %>
		<%= link_to 'お気に入り登録',favorites_path(post_id: @post.id),method: :post,class:'btn btn-primary btn-lg'%>
	<% end %>
<% end %>

app/views/users/index.html.erb
<h1>Users index</h1>
<ul class="media-list">
  <% @users.each do |user| %>
  	<li class="media">
  		<a class="media-left">
  			<h4>USER:</h4>
  		</a>
  		<div class="media-body">
  			<h4 class="media-heading"><%= user.name %></h4>
  			Register at: <%= user.created_at %>
  		</div>
  	</li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<%= form_with(model:@user,local: true)do |f| %>
<%= render 'layouts/error_messages',model: f.object %>

  <div class='user_group'>
    <%= f.label :name,'Name' %>
    <%= f.text_field :name,class:'form-control' %>
  </div>

  <div class='user_group'>
    <%= f.label :email,'Email'%>
    <%= f.email_field :email,class:'form-control'%>
  </div>

  <div class='user_group'>
    <%= f.label :password,'Password'%>
    <%= f.password_field :password,class:'form-control'%>
  </div>

  <div class='user_group'>
    <%= f.label :password_confirmation,'Confirmation'%>
    <%= f.password_field :password_confirmation,class:'form-control'%>
  </div>

  <%= f.submit 'Sign up',class:'btn btn-primary btn-block'%>
<% end %>

app/views/users/show.html.erb
<h1>User info.</h1>
<div class="panel panel-default">
	<div class="panel-heading">
		NAME: <%= @user.name %>
	</div>
	<div class="panel-body">
		EMAIL: <%= @user.email %>
	</div>
</div>